@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package com.xiaoyue.celestial_weapon;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;